### ISSUE TITLE
Importance scores in the tsv file

### ISSUE THREAD

**Issue by ayushkothari27** [yalesong/tvsum50#2]
Hello,
How should I interpret the importance scores in the tsv file? Are they for each frame? If yes, what is the frame rate used? 
What is the significance of a shot being of 2 seconds?

The data annotation file has importance scores for each video. The readme said that each shot is 2 seconds. Hence while going through the data for the 1st video (length 5 min 54 sec), the number of annotations provided was over 10000. I am not able to understand how the length of the video is related to the number of annotations. Multiplying each video duration with commonly used frame rates (24-30) doesn't help as well.

**Comment by KAISER1997** [comment]
@aayushkothari11 I had a similar doubt,did you find any answer?
